name: Build libz.dylib

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SDK_VERSION: "0.1.0"
      SDK_REPO: "acieslewicz/oss-iphoneos-sdk"
      
    steps:
    - uses: actions/checkout@v4

    - name: Download SDK
      run: |
        curl -L -o sdk.tar.gz "https://github.com/${{ env.SDK_REPO }}/releases/download/v${{ env.SDK_VERSION }}/iPhoneOS3.0-custom.sdk.tar.gz"
        tar xzf sdk.tar.gz
        chmod -R +x iPhoneOS3.0-custom.sdk/usr/bin/
      
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build
    
    - uses: actions/upload-artifact@v4
      with:
        name: libz.1.dylib
        path: build/libz.1.dylib

    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: build/libz.1.dylib

